### ISSUE TITLE
Creating Two App icons for my Application

### ISSUE THREAD

**Issue by NarenderNagpal** [AmrDeveloper/ReactButton#4]
This lib is creating Two App icons for my Application. 

<activity android:name="com.amrdeveloper.reactbuttonlibrary.MainActivity" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

How can I solve this issue so that My App should not have 2 app icons.

**Comment by AmrDeveloper** [comment]
hi bro 
thanks for you comment

this was relase 1.0.5 problem because there is intent filter in app Manifest
and this problem fixed and some features added now in relase 1.0.6 like new dialog shape 
and you can set custom shape for reations dialog 

i hope you enjoy with version 1.0.6 and next version will come soon to let you to change reactions icon , text and text color

Version 1.0.6 Available now

**Comment by NarenderNagpal** [comment]
Thanks for the prompt reply. Now it's working fine.

**Comment by pradeepknila** [comment]
Hi brother how can i set the reaction from API call i mean what method to set ?

**Comment by AmrDeveloper** [comment]
Hello @pradeepknila

Currently, the library accepts drawable and mipmap, so you can make your API return icon name and id and you used them from drawable. maybe later I will support accept image url

Thanks
Amr Hesham
